export const firstPart = [
    "Finally the day came!",
    "Eisob natok amar dara hobe na!",
    "",
    "Bhaai kaa birthday hein,",
    "Bhaai khusss rehena aur khubb uchaiyaa choona,",
    "",
    "Now stop, take a deep breath and start reading again,",
    "I don’t want you to read it fast, karon tui eta jhor er begh a porchis, just go slow on the lines,",
  ];
  
  export const restOfMessage = [
    "",
    "",
    "💫 Kuch line-o mein tujhe, tujhko samjhana tha,",
    "💫 Tu hein kaun aaj wohi baatana tha,",
    "",
    "🌸 Iss umaar mein hoh nehi payega per, ek dusre janam mei kahi,",
    "🌸 Mein aaunga tere paas, per “mein wohi hoon!” yeh bataunga mein nehi,",
    "",
    "🎈 Mein fir seh tera dost banunga, bin-bole ki “mein tera dost tha kabhi”",
    "🎈 Fir bhi mein tu bankaar, tujhe woh saab na de paau jo tune mujhe diya aabhi,",
    "",
    "🎉 Happy Birthday Tiger! 🎉",
    "🌟 God Bless you!",
    "👑 And always be the queen of your choices!",
    "",
    "r last a r ekta line likhechi, sune ja chup chaap",
    "",
    "buss dhiyaan rakhna itni si baath pe mera,",
    "tu Krishna hogi kisi aur ka,",
    "per Sudama hoon mein tera",
    "",
    "ki bhabjis sesh?",
    "hurr bal,",
    "tor bhai ki eto taratari chere debe,",
    "",
    "💐 With all due respect, presenting you the queen of the queens 💐",
    "👑 ASHMITA BANERJEE 👑",
  ];